/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.MapsCreator;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class MapSelect extends javax.swing.JFrame {

    /**
     * Creates new form MapSelect
     */
    public MapSelect() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtnMap1 = new javax.swing.JRadioButton();
        rbtnMap2 = new javax.swing.JRadioButton();
        rbtnMap3 = new javax.swing.JRadioButton();
        rbtnMap4 = new javax.swing.JRadioButton();
        rbtnMap5 = new javax.swing.JRadioButton();
        txtUsername = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        txtPort = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbtnMap1);
        rbtnMap1.setSelected(true);
        rbtnMap1.setText("Mapa 1");
        jPanel1.add(rbtnMap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        buttonGroup1.add(rbtnMap2);
        rbtnMap2.setText("Mapa 2");
        jPanel1.add(rbtnMap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 6, -1, -1));

        buttonGroup1.add(rbtnMap3);
        rbtnMap3.setText("Mapa 3");
        jPanel1.add(rbtnMap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 6, -1, -1));

        buttonGroup1.add(rbtnMap4);
        rbtnMap4.setText("Mapa 4");
        jPanel1.add(rbtnMap4, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 6, -1, -1));

        buttonGroup1.add(rbtnMap5);
        rbtnMap5.setText("Mapa 5");
        jPanel1.add(rbtnMap5, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 6, -1, -1));

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        txtUsername.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 220, -1));

        btnRegister.setBackground(new java.awt.Color(255, 255, 255));
        btnRegister.setForeground(new java.awt.Color(51, 51, 51));
        btnRegister.setText("Iniciar Juego");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 220, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 134, 389, 10));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Ingresar nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 156, -1, -1));

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("IP");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Puerto");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 96, -1, -1));
        jPanel1.add(txtIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 56, 129, -1));
        jPanel1.add(txtPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 92, 129, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, 389, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        String user = txtUsername.getText();
        int map[][];
        MapsCreator creator = new MapsCreator();
        
        if (!user.isEmpty()) {
            
            if (rbtnMap1.isSelected()) {
                map = creator.getMap1();
            } else if(rbtnMap2.isSelected()) {
                map = creator.getMap2();
            } else if(rbtnMap3.isSelected()) {
                map = creator.getMap3();
            } else if(rbtnMap4.isSelected()) {
                map = creator.getMap4();
            } else {
                map = creator.getMap5();
            }
            //creator = null;
            Window windowGame = new Window(map, user);
            windowGame.setVisible(true);
            windowGame.connect(txtIP.getText(),Integer.parseInt(txtPort.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre");
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rbtnMap1;
    private javax.swing.JRadioButton rbtnMap2;
    private javax.swing.JRadioButton rbtnMap3;
    private javax.swing.JRadioButton rbtnMap4;
    private javax.swing.JRadioButton rbtnMap5;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
