/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.BattleShipClientController;
import client.MapsCreator;
import java.awt.Graphics;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian
 */
public class Window extends javax.swing.JFrame {

    BattleShipClientController sc;
    private String username;
    private int map[][];

    /**
     * Creates new form Window
     *
     * @param map
     * @param username
     */
    public Window(int map[][], String username) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.map = map;
        this.username = username;
    }

    public void connect() {
        sc = null;
        try {
            sc = new BattleShipClientController("localhost", 25500);
        } catch (IOException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (sc != null) {
            System.out.println(sc.readText());
            sc.setMyMap(this.map);
            sc.setEnemyMap(new MapsCreator().getEmptyMap());
            panelEnemy.setMap(sc.getEnemyMap());
            panelMy.setMap(sc.getMyMap());
            panelEnemy.repaint();
            panelMy.repaint();
            sc.setPanelEnemyMap(panelEnemy);
            sc.setPanelMyMap(panelMy);
            sc.register(username);
            //
            sc.start(sc);
        }
    }

    @Override
    public void paint(Graphics grphcs) {
        //panelWindow1.paint(grphcs);
        super.paint(grphcs); //To change body of generated methods, choose Tools | Templates.

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEnemy = new gui.panelWindow();
        panelMy = new gui.panelWindow();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelEnemy.setPreferredSize(new java.awt.Dimension(600, 450));
        panelEnemy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEnemyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelEnemyLayout = new javax.swing.GroupLayout(panelEnemy);
        panelEnemy.setLayout(panelEnemyLayout);
        panelEnemyLayout.setHorizontalGroup(
            panelEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        panelEnemyLayout.setVerticalGroup(
            panelEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        panelMy.setPreferredSize(new java.awt.Dimension(600, 450));
        panelMy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMyLayout = new javax.swing.GroupLayout(panelMy);
        panelMy.setLayout(panelMyLayout);
        panelMyLayout.setHorizontalGroup(
            panelMyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        panelMyLayout.setVerticalGroup(
            panelMyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelEnemy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1))
                    .addComponent(panelMy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        if (JOptionPane.showConfirmDialog(this,
                "Estás seguro que deseas dejar el juego?", "Cerrar juego",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
            sc.exitGame();
            //System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void panelEnemyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEnemyMouseClicked

        int row = (int) evt.getY() / 15;
        int column = (int) evt.getX() / 15;
        System.out.println(row + ", " + column);
        if(!sc.attack(row, column)) {
            JOptionPane.showMessageDialog(this, "Aún no es tu turno.");
        }
    }//GEN-LAST:event_panelEnemyMouseClicked

    private void panelMyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMyMouseClicked
        int row = (int) evt.getY() / 15;
        int column = (int) evt.getX() / 15;
        if (sc.createShip(row, column)) {
            System.out.println("Creado");
        }
    }//GEN-LAST:event_panelMyMouseClicked
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Window().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private gui.panelWindow panelEnemy;
    private gui.panelWindow panelMy;
    // End of variables declaration//GEN-END:variables

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}
